server:
  port: 8081

spring:
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate.ddl-auto: update
      show-sql: true
      hibernate.format_sql : true
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:testdb
    username: saran
    password: saran
  h2:
    console:
      enabled: true

logging:
  level:
    ROOT: INFO
    org.hibernate:
      SQL: INFO
      type: INFO



